language: node_js
node_js:
  - '12'
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
before_install:
  - npm cache clean --force
script:
  - npm run lint
  - npm run test
  - npm run build
notifications:
  email:
    recipients:
      - getsaf@gmail.com
    on_success: change
    on_failure: change
